name: catapiljaapp
description: The Library for Catapilja cloud apps
version: 0.13.16
repository: https://github.com/obandu/catapilja_app
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '3.10.7'

dependencies:
  intl: 0.20.2
  http: 1.6.0

